kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-dns-performance
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-dns-performance
  template:
    metadata:
      labels:
        app: nodejs-dns-performance
    spec:
      containers:
        - name: nodejs-dns-performance
          image: 'docker.io/number9/nodejs-dns-performance:latest'
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: nodejs-dns-performance-service
  namespace: default
  labels:
    app: nodejs-dns-performance-service
spec:
  ports:
    - name: main
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: nodejs-dns-performance
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
